name: Auto-merge

on:
  push:
    branches:
      - dependabot/npm_and_yarn/DEMO/**
  pull_request:

jobs:
  auto-merge:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3
     
    - name: Auto-merge PR
      uses: ahmadnassri/action-dependabot-auto-merge@v2
